### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by ueffel** [TanninOne/keypirinha-allmygames#17]
The new version (1.7.2) errors while cataloging:

```plain
12:28:15.616 ** ERROR: AllMyGames.AllMyGames: [Steam] Failed to parse appinfo.vdf Traceback (most recent call last):
  File "C:\Users\ueffel\AppData\Roaming\Keypirinha\InstalledPackages\AllMyGames.keypirinha-package\lib\steam\steam.py", line 208, in __get_appinfo
TypeError: parse_appinfo() takes 1 positional argument but 2 were given
12:28:15.634 WARNING: AllMyGames.AllMyGames: failed to initialize repo Steam Traceback (most recent call last):
  File "C:\Users\ueffel\AppData\Roaming\Keypirinha\InstalledPackages\AllMyGames.keypirinha-package\allmygames.py", line 66, in on_catalog
  File "C:\Users\ueffel\AppData\Roaming\Keypirinha\InstalledPackages\AllMyGames.keypirinha-package\lib\steam\steam.py", line 111, in __init__
  File "C:\Users\ueffel\AppData\Roaming\Keypirinha\InstalledPackages\AllMyGames.keypirinha-package\lib\steam\steam.py", line 211, in __get_appinfo
  File "C:\Users\ueffel\AppData\Roaming\Keypirinha\InstalledPackages\AllMyGames.keypirinha-package\lib\steam\steam.py", line 208, in __get_appinfo
TypeError: parse_appinfo() takes 1 positional argument but 2 were given
```

**Comment by ueffel** [comment]
Fixed with 1.7.3.
