### ISSUE TITLE
PermissionError when searching

### ISSUE THREAD

**Issue by jack128** [TanninOne/keypirinha-allmygames#8]
tried to use your plugin and got error in console and **did not get** my games in catalog

```
00:02:31.364 AllMyGames.AllMyGames: [Steam] new libraries format
00:02:31.998 WARNING: AllMyGames.AllMyGames: failed to initialize repo GOG [WinError 2] The system cannot find the file specified
00:02:32.067 AllMyGames.AllMyGames: Games found ['Steam: 94', 'Epic Games Store: 2', 'Windows Store: 23', 'Origin: 0', 'UPlay: 3']
00:02:34.029 ** ERROR: Error from AllMyGames.AllMyGames.on_catalog: <class 'PermissionError'>: [Errno 13] Permission denied: 'C:/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/data/games/'
Traceback (most recent call last):
  File "C:\PortableApps\KeyPirinha\portable\Profile\InstalledPackages\AllMyGames.keypirinha-package\allmygames.py", line 102, in on_catalog
  File "C:\PortableApps\KeyPirinha\portable\Profile\InstalledPackages\AllMyGames.keypirinha-package\allmygames.py", line 102, in <genexpr>
  File "C:\PortableApps\KeyPirinha\portable\Profile\InstalledPackages\AllMyGames.keypirinha-package\allmygames.py", line 112, in make_item
  File "C:\PortableApps\KeyPirinha\portable\Profile\InstalledPackages\AllMyGames.keypirinha-package\allmygames.py", line 151, in get_icon
```
I think this screenshot explain everything (see DisplayIcon value)
![image](https://user-images.githubusercontent.com/883874/137991736-207d4879-ce5b-4a9a-869f-1c5985b56974.png)

I believe it would be OK if game displays without icon, we need try catch or something..

**Comment by TanninOne** [comment]
fixed in v1.5
sorry this took so long
